// Code generated by goctl. DO NOT EDIT.
// Source: app.proto

package server

import (
	"context"

	"github.com/cherish-chat/imcloudx-server/app/app/internal/logic/appservice"
	"github.com/cherish-chat/imcloudx-server/app/app/internal/svc"
	"github.com/cherish-chat/imcloudx-server/common/pb"
)

type AppServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedAppServiceServer
}

func NewAppServiceServer(svcCtx *svc.ServiceContext) *AppServiceServer {
	return &AppServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *AppServiceServer) VerifyClient(ctx context.Context, in *pb.VerifyClientReq) (*pb.VerifyClientResp, error) {
	l := appservicelogic.NewVerifyClientLogic(ctx, s.svcCtx)
	return l.VerifyClient(in)
}
