// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.12
// source: common.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SDPType describes the type of an SessionDescription.
type SDPType int32

const (
	SDPType_SDPTypeUnkown SDPType = 0
	// SDPTypeOffer indicates that a description MUST be treated as an SDP
	// offer.
	SDPType_SDPTypeOffer SDPType = 1
	// SDPTypePranswer indicates that a description MUST be treated as an
	// SDP answer, but not a final answer. A description used as an SDP
	// pranswer may be applied as a response to an SDP offer, or an update to
	// a previously sent SDP pranswer.
	SDPType_SDPTypePranswer SDPType = 2
	// SDPTypeAnswer indicates that a description MUST be treated as an SDP
	// final answer, and the offer-answer exchange MUST be considered complete.
	// A description used as an SDP answer may be applied as a response to an
	// SDP offer or as an update to a previously sent SDP pranswer.
	SDPType_SDPTypeAnswer SDPType = 3
	// SDPTypeRollback indicates that a description MUST be treated as
	// canceling the current SDP negotiation and moving the SDP offer and
	// answer back to what it was in the previous stable state. Note the
	// local or remote SDP descriptions in the previous stable state could be
	// null if there has not yet been a successful offer-answer negotiation.
	SDPType_SDPTypeRollback SDPType = 4
)

// Enum value maps for SDPType.
var (
	SDPType_name = map[int32]string{
		0: "SDPTypeUnkown",
		1: "SDPTypeOffer",
		2: "SDPTypePranswer",
		3: "SDPTypeAnswer",
		4: "SDPTypeRollback",
	}
	SDPType_value = map[string]int32{
		"SDPTypeUnkown":   0,
		"SDPTypeOffer":    1,
		"SDPTypePranswer": 2,
		"SDPTypeAnswer":   3,
		"SDPTypeRollback": 4,
	}
)

func (x SDPType) Enum() *SDPType {
	p := new(SDPType)
	*p = x
	return p
}

func (x SDPType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SDPType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[0].Descriptor()
}

func (SDPType) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[0]
}

func (x SDPType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SDPType.Descriptor instead.
func (SDPType) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

//WebsocketCustomCloseCode websocket关闭码
//You can define custom codes in the 3000-4999 range.
//The 3000-3999 range is reserved for use by libraries, frameworks and applications.
//The 4000-4999 range is reserved for private use.
type WebsocketCustomCloseCode int32

const (
	WebsocketCustomCloseCode_CloseCodeZero                 WebsocketCustomCloseCode = 0    // pb必须有一个默认值
	WebsocketCustomCloseCode_CloseCodeAuthenticationFailed WebsocketCustomCloseCode = 4001 // 认证失败
	WebsocketCustomCloseCode_CloseCodeDuplicateConnection  WebsocketCustomCloseCode = 4002 // 重复连接
	WebsocketCustomCloseCode_CloseCodeServerInternalError  WebsocketCustomCloseCode = 4003 // 服务器内部错误
	WebsocketCustomCloseCode_CloseCodeHeartbeatTimeout     WebsocketCustomCloseCode = 4004 // 心跳超时
)

// Enum value maps for WebsocketCustomCloseCode.
var (
	WebsocketCustomCloseCode_name = map[int32]string{
		0:    "CloseCodeZero",
		4001: "CloseCodeAuthenticationFailed",
		4002: "CloseCodeDuplicateConnection",
		4003: "CloseCodeServerInternalError",
		4004: "CloseCodeHeartbeatTimeout",
	}
	WebsocketCustomCloseCode_value = map[string]int32{
		"CloseCodeZero":                 0,
		"CloseCodeAuthenticationFailed": 4001,
		"CloseCodeDuplicateConnection":  4002,
		"CloseCodeServerInternalError":  4003,
		"CloseCodeHeartbeatTimeout":     4004,
	}
)

func (x WebsocketCustomCloseCode) Enum() *WebsocketCustomCloseCode {
	p := new(WebsocketCustomCloseCode)
	*p = x
	return p
}

func (x WebsocketCustomCloseCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WebsocketCustomCloseCode) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[1].Descriptor()
}

func (WebsocketCustomCloseCode) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[1]
}

func (x WebsocketCustomCloseCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WebsocketCustomCloseCode.Descriptor instead.
func (WebsocketCustomCloseCode) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

var File_common_proto protoreflect.FileDescriptor

var file_common_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02,
	0x70, 0x62, 0x2a, 0x6b, 0x0a, 0x07, 0x53, 0x44, 0x50, 0x54, 0x79, 0x70, 0x65, 0x12, 0x11, 0x0a,
	0x0d, 0x53, 0x44, 0x50, 0x54, 0x79, 0x70, 0x65, 0x55, 0x6e, 0x6b, 0x6f, 0x77, 0x6e, 0x10, 0x00,
	0x12, 0x10, 0x0a, 0x0c, 0x53, 0x44, 0x50, 0x54, 0x79, 0x70, 0x65, 0x4f, 0x66, 0x66, 0x65, 0x72,
	0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x53, 0x44, 0x50, 0x54, 0x79, 0x70, 0x65, 0x50, 0x72, 0x61,
	0x6e, 0x73, 0x77, 0x65, 0x72, 0x10, 0x02, 0x12, 0x11, 0x0a, 0x0d, 0x53, 0x44, 0x50, 0x54, 0x79,
	0x70, 0x65, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x10, 0x03, 0x12, 0x13, 0x0a, 0x0f, 0x53, 0x44,
	0x50, 0x54, 0x79, 0x70, 0x65, 0x52, 0x6f, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x10, 0x04, 0x2a,
	0xb7, 0x01, 0x0a, 0x18, 0x57, 0x65, 0x62, 0x73, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x43, 0x75, 0x73,
	0x74, 0x6f, 0x6d, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x11, 0x0a, 0x0d,
	0x43, 0x6c, 0x6f, 0x73, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x5a, 0x65, 0x72, 0x6f, 0x10, 0x00, 0x12,
	0x22, 0x0a, 0x1d, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x41, 0x75, 0x74, 0x68,
	0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64,
	0x10, 0xa1, 0x1f, 0x12, 0x21, 0x0a, 0x1c, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x43, 0x6f, 0x64, 0x65,
	0x44, 0x75, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x10, 0xa2, 0x1f, 0x12, 0x21, 0x0a, 0x1c, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x43,
	0x6f, 0x64, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x10, 0xa3, 0x1f, 0x12, 0x1e, 0x0a, 0x19, 0x43, 0x6c, 0x6f,
	0x73, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x54,
	0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x10, 0xa4, 0x1f, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData = file_common_proto_rawDesc
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_proto_rawDescData)
	})
	return file_common_proto_rawDescData
}

var file_common_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_common_proto_goTypes = []interface{}{
	(SDPType)(0),                  // 0: pb.SDPType
	(WebsocketCustomCloseCode)(0), // 1: pb.WebsocketCustomCloseCode
}
var file_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		EnumInfos:         file_common_proto_enumTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_rawDesc = nil
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
