---
apiVersion: v1
kind: Service
metadata:
  name: app-svc
  namespace: imcloudx
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: port-1
      port: 12302
      protocol: TCP
      targetPort: 12302
  selector:
    app: app
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-svc
  namespace: imcloudx
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http
      port: 12300
      protocol: TCP
      targetPort: 12300
    - name: rpc
      port: 12301
      protocol: TCP
      targetPort: 12301
  selector:
    app: gateway
  sessionAffinity: None
  type: ClusterIP
---
